name: Create New Tag on Push

on:
 workflow_dispatch:
    input_text:
        description: Enter your commit want rollback
        required: false
        type: text
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ip: [1,2]
      fail-fast: true
      max-parallel: 1
    
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Write to File
        run: |
          env
          echo "123"
