name: Create New Tag on Push

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Get Latest Commit Hash
        id: get_commit
        run: |
          echo "::set-output name=commit_hash::$(git rev-parse HEAD)"

      - name: Create New Tag
        run: |
          tag_name="v1.0.0-$(date +%Y%m%d%H%M%S)"
          git tag $tag_name "${{ steps.get_commit.outputs.commit_hash }}"
          git push origin $tag_name
