name: Create New Tag on Push

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create New Tag
        run: |
          tag_name="v1.0.0-$(date +%Y%m%d%H%M%S)"
          git tag $tag_name
          git push origin $tag_name
