name: Create New Tag on Push

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ip: [1,2]
      fail-fast: true
      max-parallel: 1
    
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Write to File
        run: |
          echo "This is version 1" >> text.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: text-file
          path: text.txt

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: text-file

      - name: Read from File
        run: |
          cat text.txt
        
