name: Create New Tag on Push

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create tag name
        id: create_tag_name
        run: |
          echo "tag_name=v1.3.0" >> $GITHUB_OUTPUT
          echo "tag_name_gh=v1.3.1" >> $GITHUB_OUTPUT
        

      - name: Create New Tag
        run: |
          echo "${{ steps.create_tag_name.outputs.tag_name }}"
          tag_name="${{ steps.create_tag_name.outputs.tag_name }}"
          git tag $tag_name
          git push origin $tag_name

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ steps.create_tag_name.outputs.tag_name }}"
          release_name: Release "${{ steps.create_tag_name.outputs.tag_name }}"
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: Get Tags
        run: |
          git tag -l

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag_name="${{ steps.create_tag_name.outputs.tag_name_gh }}"
          gh release create $tag_name -t "Release $tag_name" -n "Description for Release $tag_name"
