name: SSH Pull Code

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH }}

      - name: SSH to server and pull code
        run: |
          ssh -o StrictHostKeyChecking=no -A ohioncom@103.106.105.141 'ls'
