name: SSH Pull Code

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH key
        uses: longaodai/ssh@v1.0.5
        with:
          # ssh-private-key: ${{ secrets.SSHKEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          command: 'ls -l'

      # - name: SSH to server and pull code
      #   run: |
      #     ssh -o StrictHostKeyChecking=no -A ohioncom@103.106.105.141 'cd test-deploy.hioncoding.com && git pull origin'
