name: DEV - Manual

on:
  workflow_dispatch:
    inputs:
      environment: 
        required: true
        default: 'Stop'
        description: Please select the action
        type: choice
        options:
          - stop
          - start
      input_text:
        description: Enter your commit want rollback
        required: false
        type: text

jobs:
  deployment:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Show Input Text
        if: always()
        run: |
          echo ${{ github.token }}
          echo "Branch: ${GITHUB_REF##*/}"
          echo "Tag: ${{ inputs.version }}"
          echo "Input text: ${{ github.event.inputs.input_text }}"

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: 'longaodai/dockers'
          token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          ref: 'main'
          path: 'another'

      - name: Show file
        run: |
          ls -la
          cd another
          ls -la
