name: DEV - Manual

on:
  workflow_dispatch:
    inputs:
      environment: 
        required: true
        default: 'Stop'
        description: Please select the FW action
        type: choice
        options:
          - stop
          - start
      input_text:
        description: Enter your text
        required: true
        type: text

jobs:
  deployment:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Run 2
        if: always()
        run: |
          echo "Run 2"

      - name: Show Input Text
        run: |
          echo "Input text: ${{ github.event.inputs.input_text }}"

      - name: Run 3
        run: |
          echo "Run 3"
