name: DEV - Rollback

on:
  push:
    branches:
      - main
      
  workflow_dispatch:
    inputs:
      input_text:
        description: Enter your commit want rollback
        required: true
        type: text

jobs:
  deployment:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Last Commits
        id: last_commits
        run: |
          commits=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          "https://api.github.com/repos/${{ github.repository }}/commits?per_page=5")
          echo "::set-output name=commits::$commits"

      - name: Extract Commit IDs
        id: extract_commit_ids
        run: |
          commit_ids=""
          for commit in $(echo "${{ steps.last_commits.outputs.commits }}" | jq -r '.[] | .sha'); do
            commit_ids="$commit_ids $commit"
          done
          echo "::set-output name=commit_ids::$commit_ids"

      - name: Show Commit IDs
        run: echo ${{ steps.last_commits.outputs.commits }}

      - name: Run 2
        run: echo "Run 2"

      - name: Show Input Text
        run: |
          echo ${{ github.event.inputs.input_text }}

      - name: Run 3
        run: echo "Run 3"
