name: Shedule

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Notification
        run: |
          echo "Say hello!"
      
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: check
        if: always()
        run: |
          echo "Branch: ${GITHUB_REF##*/}"
          cat README.MD
